# Generated by Django 4.1.3 on 2022-12-20 21:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="name2",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nome2"),
        ),
        migrations.AddField(
            model_name="organization",
            name="name2_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome2"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="name2_pt_br",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome2"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="slug2",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="Slug2",
            ),
        ),
    ]
